#! /bin/bash

#===== Prerequisitos de Instalacion para BD Oracle

yum clean all
yum -y update
yum install -y elfutils-*
yum install -y glibc-*
yum install -y gcc-4*
yum install -y gcc-c++*
yum install -y libstdc++*
yum install -y glibc-headers*
yum install -y libgomp*
yum install -y compat-libstdc++*
yum install -y libaio-*
yum install -y sysstat*
yum install -y unixODBC
yum install -y unixODBC*
yum install -y rsh-*
yum install -y ksh
yum groupinstall -y "X Window System"
yum install -y xorg-x11-apps
yum install -y compat-libcap*
yum install -y telnet
yum install -y tuned
yum install -y nfs-utils
yum install -y unzip
subscription-manager repos --enable rhel-7-server-optional-rpms
yum install -y compat-libstdc++-33


#echo "INICIA PARTE PARA LA CREACION DE GRUPOS Y USUARIOS PARA ORACLE"

chown -R oracle:oinstall /grid/
chown -R oracle:oinstall /oracle11G/
chown -R oracle:oinstall /oradump/
chown -R oracle:oinstall /oradata/

chmod -R 775 /grid
chmod -R 775 /oracle11G
chmod -R 775 /oradump
chmod -R 775 /oradata

sleep 2

echo "INICIA CONFIGURACION DE PARAMETROS DEL KERNEL Y PROFILES"

cat >>/etc/sysctl.conf<<EOF
kernel.shmmni = 4096
kernel.sem = 250 32000 100 128
fs.file-max = 6815744
fs.aio-max-nr=1048576
net.ipv4.ip_local_port_range = 9000 65500
net.core.rmem_default=4194304
net.core.wmem_default=262144
net.core.rmem_max=4194304
net.core.wmem_max=1048576
EOF

sleep 2

/sbin/sysctl -p

cat >>/etc/security/limits.conf<<EOF
oracle soft nproc 2047
oracle hard nproc 16384
oracle soft nofile 1024
oracle hard nofile 65536
EOF

cat >>/etc/security/limits.conf<<EOF
grid soft nproc 2047
grid hard nproc 16384
grid soft nofile 1024
grid hard nofile 65536
EOF

cat >>/etc/pam.d/login<<EOF
session required pam_limits.so
EOF

cat >>/etc/profile<<EOF
if [ \$USER = "oracle" ]; then
if [ \$SHELL = "/bin/ksh" ]; then
ulimit -p 16384
ulimit -n 65536
else
ulimit -u 16384 -n 65536
fi
umask 022
fi
EOF

cat >>/etc/profile<<EOF
if [ \$USER = "grid" ]; then
if [ \$SHELL = "/bin/ksh" ]; then
ulimit -p 16384
ulimit -n 65536
else
ulimit -u 16384 -n 65536
fi
umask 022
fi
EOF

cat >>/etc/csh.login<<EOF
if ( \$USER == "oracle" ) then
limit maxproc 16384
limit descriptors 65536
umask 022
endif
EOF

cat >>/etc/csh.login<<EOF
if ( \$USER == "grid" ) then
limit maxproc 16384
limit descriptors 65536
umask 022
endif
EOF

echo "INICIA CONFIGURACION DEL RLOGIN"
chkconfig rsh on
sleep 2
chkconfig rlogin on
sleep 2
service xinetd reload
sleep 2

mv /usr/kerberos/bin/rsh /usr/kerberos/bin/rsh.original
mv /usr/kerberos/bin/rcp /usr/kerberos/bin/rcp.original
mv /usr/kerberos/bin/rlogin /usr/kerberos/bin/rlogin.original
